# Generated by Django 5.1.5 on 2025-02-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phoneno',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
